<?php
/*
 * fields_product_page.inc
 * defines the variables and creates the arrays required to display the product
 * page of the catalogArrays
 */
$page = array(
    "title" => "Der Baumarkt - Katalog",
    "top" => "Der Baumarkt - Katalog",
    "bottom" => "Bei Fragen oder Problemen wenden Sie sich an admin@baumarkt.de"
);
$table_heads = array(
    "katalog_nr" => "Kat.Nr.",
    "name" => "Bezeichnung",
    "pr_beschr" => "Beschreibung",
    "preis" => "Preis",
    "menge" => "Menge"
);
?>